resources:
- name: app-sources
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemoDocker
    branch: master
    
- name: docker-image-agency
  type: docker-image
  source:
    repository: smichard/agencydemo
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}
    
- name: staging-CloudFoundry
  type: cf
  source:
    api: {{pws_api}}
    username: {{pws_user}}
    password: {{pws_password}}
    organization: {{pws_org}}
    space: {{pws_space}}
    skip_cert_check: false

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: app-sources
    trigger: true
  - put: docker-image-agency
    params:
        build: app-sources

- name: deploy-app
  plan:
    - get: docker-image-agency
      trigger: true
      passed: [build-docker-image]
    - put: staging-CloudFoundry
      params:
        manifest: app-sources/manifest.yml