resources:
- name: app-sources
  type: git
  source:
    uri: https://github.com/smichard/CloudFoundryDemoDocker
    branch: master
       
- name: staging-CloudFoundry
  type: cf
  source:
    api: {{pws_api}}
    username: {{pws_user}}
    password: {{pws_password}}
    organization: {{pws_org}}
    space: {{pws_space}}
    skip_cert_check: false

jobs:
- name: deploy-website
  serial: true
  plan:
  - get: app-sources
    trigger: true
  - put: staging-CloudFoundry
    params:
        manifest: app-sources/manifest.yml